<a href="https://colab.research.google.com/github/2303a51852/Python-for-DataScience/blob/main/lab3%2C25_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#zeros array
zeros_arr=np.zeros((3,3))
print("Zeros Array:\n",zeros_arr)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones Array
ones_arr=np.ones((2,4))
print("Ones Array:\n",ones_arr)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Array Attributes
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("Demensions:",arr.ndim)
print("Data Type:",arr.dtype)
print("Size:",arr.size)
print("Item Size",arr.itemsize)

shape: (2, 3)
Demensions: 2
Data Type: int64
Size: 6
Item Size 8


In [ ]:
#Array Indexing and slicing
import numpy as np
arr=np.array([10,20,30,40,50])
print("First elemnet:",arr[0])
print("Last elemnt:",arr[-1])
print("Slice[1:4]",arr[1:4])
print("Every second element:",arr[::2])

First elemnet: 10
Last elemnt: 50
Slice[1:4] [20 30 40]
Every second element: [10 30 50]


In [ ]:

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

arr=np.array([0,np.pi/2,np.pi])
print("Sin values:",np.sin(arr))
print("Cos values:",np.cos(arr))
print("Square root:",np,sqrt([1,4,9]))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
Sin values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


NameError: name 'sqrt' is not defined

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

In [ ]:
#Broadcasting
a=np.array([1,2,3])
b=5
print(a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print(c+d)


In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))
print(A.T)
print(np.linalg.inv(A))
print(np.linalg.det(A))

In [ ]:
#Sample program -Student Marks Analysis
import numpy as np
#marks in three subjects
marks=np.array([85,90,88],[78,81,85],[92,89,93])
print(np.mean(marks,axis=0))
print(np.mean(marks,axis=1))
print(np.max(marks,axis=0))
print(np.min(marks,axis=0))
